import SearchIcon from "../images/search.svg";
import SelectIcon from "../images/select.svg";
import StandOutIcon from "../images/stand-out.svg";

const featuresObj = [
  {
    title: "Search",
    description:
      "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
    image: SearchIcon,
  },
  {
    title: "Select",
    description:
      "Choose from thousands of options generated by the slogan maker that fit your needs.",
    image: SelectIcon,
  },
  {
    title: "Stand Out",
    description: "Congrats on your new slogan. It's time to win the world!",
    image: StandOutIcon,
  },
];

const Features = () => {
  return (
    <div className="p-4 bg-primary/10">
      <div className="w-[min(1024px,_100%)] mx-auto py-6 flex flex-row items-start justify-center gap-8 flex-wrap">
        {featuresObj.map((feature) => (
          <div className="max-w-[320px] flex flex-col items-center justify-start gap-2" key={feature.title}>
            <img src={feature.image} alt="logo" />
            <p className="font-galano-medium text-lg">{feature.title}</p>
            <p className="text-[hsl(0,_0%,_30%)] text-center">
              {feature.description}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Features;
